### ISSUE TITLE
OnConfigurationChanged is never called and OnDestroyed is still called even when adding ConfigChange attributes to Activity in Xamarin-Forms Android App

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#1561]
I am using Xamarin-Forms with .NETStandard 2.0.

This page [(https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/handling-rotation)](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/handling-rotation) explains how to manually handle orientation changes by providing OnConfigurationChanged handler.

Orientation change is not the only reason Android decides to send an Activity to OnDestroy callback.  Others are config changes such as attaching an external keyboard and Android provides `ConfigChange.Keyboard` and `ConfigChange.KeyboardHidden` which can be added to Activity attributes just as the `Orientation `was added to nicely explain how to handle orientation changes manually in this article.

So, using the same logic, if I add `ConfigChange.Keyboard` and `ConfigChange.KeyboardHidden` attribues to my Activity, I would expect to see my `OnHandleConfigurationChanges `callback **to be fired** and mine `OnDestroy `callback **NOT to be fired** based on this documentation (as it states, adding these attributes will prevent activity from restarting).  Here is my Activity

```
[Activity(Name="com.my.domain.mainactivity", 
   Label="...",
   Icon= "...",
   Theme="...",
   ConfigurationChanges=ConfigChanges.Keyboard
      | ConfigChanges.KeyboardHidden
      | ConfigChanges.ScreenSize
      | ConfigChanges.ScreenLayout
      | ConfigChanges.Orientation)]
public class MainActivity : Xamarin.Forms.Platform.Android.FormsAppCompatActivity
{
  ...
}
```

As you can see above, I added both attributes for `Orientation `and `Keyboard`.  As far as I understand this documentation, this means that my `MainActivity OnDestroy` callback **will not be called** since these attributes prevent activity from being restarted AND my `OnConfigurationChanged `callback **will be called** to allow me to manually handle the change.  Here is my `OnConfigurationChanged`:

```
public override void OnConfigurationChanged(Configuration newConfig)
{
   base.OnConfigurationChanged(newConfig);
   if (newConfig.Keyboard == KeyboardType.NoKeys) {....}
   else {....}
}
```

The problem is that even though I added these attributes, I still see `OnDestroy `being called and `OnConfigurationChanged `is NEVER being called.

Also, I think your document is missing part of what happens if you do not provide override for `OnConfigurationChanged `and what happens in that case.  Based on android documentation, in that case, following happens:

_"If you don't need to update your application based on these configuration changes, you can instead not implement` onConfigurationChanged()`."_
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f3f45bd-e23b-25a7-01e1-55fc444ad680
* Version Independent ID: 0717b153-921b-2033-5968-6e44430829a9
* Content: [Handling Rotation - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/handling-rotation)
* Content Source: [docs/android/app-fundamentals/handling-rotation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/handling-rotation.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @dinobu are you also seeing the methods not being hit in the [sample code](https://developer.xamarin.com/samples/monodroid/ApplicationFundamentals/RotationDemo/)?

If not, perhaps there is a product issue here that needs to be raised to the engineering team. You can do so from within [Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019), or [visit GitHub](https://github.com/xamarin/xamarin-android) (Xamarin.Android is open-source).

Thanks for the comment on the documentation - we'll keep that in mind for a future update.

**Comment by dinobu** [comment]
> 
> 
> Hi @dinobu are you also seeing the methods not being hit in the [sample code](https://developer.xamarin.com/samples/monodroid/ApplicationFundamentals/RotationDemo/)?
> 
> If not, perhaps there is a product issue here that needs to be raised to the engineering team. You can do so from within [Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019), or [visit GitHub](https://github.com/xamarin/xamarin-android) (Xamarin.Android is open-source).
> 
> Thanks for the comment on the documentation - we'll keep that in mind for a future update.

Hi Craig and thanks for your lightening responses.  I havent tried the sample code but I would like to add that I am getting now exactly what I expect, so my initial comment above can be ignored.  I would only suggest adding more to documentation regarding the last part "what happen when the override ONConfigurationChanged" is not provided as that seam to be missing.  Otherwise, this can be closed, it was my PEBKAC.  Appologies.

**Comment by conceptdev** [comment]
10 points for PEBKAC! that's one of my favorite acronyms :) Glad you got it working at least - I'll close issue this off, but make a note on our backlog about the doc suggestion. Thanks for the feedback.

**Comment by dinobu** [comment]
Done and thanks again

**Comment by erict-powersoft** [comment]
@dinobu, could you please describe your PEBKAC, since I have the same problem - I added the ConfigurationChanges flags which correctly end up in the manifest, and I also have an ONConfigurationChanged override method, which gets called. But, when adding or removing a bluetooth keyboard, I still get: OnConfigurationChanged/OnPause/OnStop/OnDestroy/OnCreate/OnStart/OnResume.  I want the keyboard action to only do the ONConfigurationChanged - and I don't see what I'm doing wrong.
Thanks!
